AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sfn-Loan

  Sample SAM Template for sfn-Loan

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  LoanScreening:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: sfn-Loan-Screening
      CodeUri: sfn-Loan-Screening/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
  DepositIntoAccount:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: sfn-Deposit-into-Account
      CodeUri: sfn-Deposit-into-Account/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
  NoticeOfPassed:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: sfn-Notice-of-Passed
      CodeUri: sfn-Notice-of-Passed/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
  NoticeOfFailed:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: sfn-Notice-of-Failed
      CodeUri: sfn-Notice-of-Failed/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
  OtherLoanRecommendations:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: sfn-Other-Loan-Recommendations
      CodeUri: sfn-Other-Loan-Recommendations/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64


